meta_product_name: "Job Kitchen"
meta_title: "Job Kitchen - לוח דרושים בתחום המזון והמשקאות"
meta_description: "הלוח דרושים בתחום המזון והמשקאות של ישראל"
meta_image: "cover.png" # should exist in `app/assets/images/`
